# Generated by Django 5.0.14 on 2026-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=20, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('start_date', models.DateTimeField(verbose_name='fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='offers', to='products.product', verbose_name='productos')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['-start_date'],
            },
        ),
    ]
