# Generated by Django 5.0.14 on 2026-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='stock minimo'),
        ),
    ]
