# Generated by Django 5.0.14 on 2026-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_featured_product_min_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='unidades por pack'),
        ),
    ]
